CREATE TABLE [EJournal].[ProjectGroups] (
	[Id] INT IDENTITY(1, 1) NOT NULL
	,[Name] NVARCHAR(100) NOT NULL
	,[IdProject] INT NOT NULL
	,[Mark] INT   CONSTRAINT [DF__ProjectGroups__Mark__239E4DCF] DEFAULT((100)) NOT NULL
	,CONSTRAINT [PK_PROJECTGROUPS] PRIMARY KEY CLUSTERED ([Id] ASC)
	);
